DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS user_info;

CREATE TABLE test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  some_text TEXT UNIQUE NOT NULL,
  another_text TEXT NOT NULL,
  a_date DATETIME
);

CREATE TABLE user_info (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_height NUMERIC NOT NULL,
  chair_height NUMERIC NOT NULL,
  table_height NUMERIC NOT NULL,
  updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);