DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS heat;

CREATE TABLE test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  some_text TEXT UNIQUE NOT NULL,
  another_text TEXT NOT NULL,
  a_date DATETIME
);

CREATE TABLE heat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  headrest INTEGER NOT NULL,
  backrest INTEGER NOT NULL,
  armrest INTEGER NOT NULL,
  bumrest INTEGER NOT NULL,
  moment DATETIME
);