DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS heat;
DROP TABLE IF EXISTS user_info;

CREATE TABLE test (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  some_text TEXT UNIQUE NOT NULL,
  another_text TEXT NOT NULL,
  a_date DATETIME
);

CREATE TABLE heat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  headrest INTEGER NOT NULL,
  backrest INTEGER NOT NULL,
  armrest INTEGER NOT NULL,
  bumrest INTEGER NOT NULL,
  moment DATETIME
);
);

CREATE TABLE user_info (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_height NUMERIC NOT NULL,
  chair_height NUMERIC NOT NULL,
  desk_height NUMERIC NOT NULL,
  updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);